### ISSUE TITLE
Extinct coin - ERROR

### ISSUE THREAD

**Issue by criptonauta** [BenjiLee/psd#1]
Hey Benji

Got the error below. I believe it's because there are currencies that are not traded anymore,

Regards,

Cripto

$ python poloniex.py -a GetOverview
-----Deposit/Withdrawal History-----
------------------------------------
--Currency=Deposit-Withdrawal=Total-
EBT=84420.685385-0=84420.685385
DASH=0.05-0=0.05
XCP=85.55534115-0=85.55534115
REP=244.11774949-0=244.11774949
BTC=0.15798327-0.34312576=-0.18514249
Traceback (most recent call last):
  File "poloniex.py", line 64, in <module>
    main()
  File "poloniex.py", line 56, in main
    actions[args.action]['function']()
  File "D:\POLO\ash\analyzer.py", line 27, in get_overview
    balance = dw_history.get_btc_balance(public_api.return_ticker())
  File "D:\POLO\ash\poloniex_apis\api_models\deposit_withdrawal_history.py", line 27, in get_btc_balance
    balance += amount * float(ticker_data[u'BTC_' + deposit]['last'])
KeyError: u'BTC_EBT'

**Comment by BenjiLee** [comment]
You commented in the wrong repo! I'll try to address this and tag this issue.
